services:
  pg:
    image: bitnami/postgresql:latest
    # environment:
    #   POSTGRES_USER: "docker"
    #   POSTGRES_PASSWORD: "docker"
    #   POSTGRES_DB: "reposhift-saas"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
