name: Run Unit Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: reposhift
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1. Checkout do código
      - uses: actions/checkout@v3

      # 2. Configurar Node.js e PNPM
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar PNPM globalmente
      - name: Install PNPM
        run: npm install -g pnpm

      # 4. Instalar dependências
      - name: Install dependencies
        run: pnpm install

      # 5. Definir variáveis de ambiente no arquivo .env
      - name: Configure environment variables
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/reposhift?schema=public" >> .env
          echo "WEB_URL=http://localhost:3000" >> .env
          echo "POSTGRES_DB=reposhift" >> .env
          echo "NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}" >> .env

      # 6. Rodar testes unitários
      - name: Run Unit Tests
        run: pnpm run test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/reposhift?schema=public
          WEB_URL: http://localhost:3000
          POSTGRES_DB: reposhift
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
