name: Run Unit Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: reposhift
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1. Checkout do código
      - uses: actions/checkout@v3

      # 2. Configurar Node.js e PNPM
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar PNPM globalmente
      - name: Install PNPM
        run: npm install -g pnpm

      # 4. Instalar dependências
      - name: Install dependencies
        run: pnpm install

      # 6. Rodar testes unitários
      - name: Run Unit Tests
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          WEB_URL: ${{ secrets.WEB_URL }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
        run: pnpm run test
        
